module.exports.descriptors = [
  'Whispering',
  'Pine',
  'Meadow',
  'Riverbend',
  'Sunset',
  'Lakeside',
  'Mountainview',
  'Hidden',
  'Tranquil',
  'Rustic',
  'Serene',
  'Wilderness',
  'Oasis',
  "Nature's",
  'Timber',
  'Wildflower',
  'Shady',
  'Adventure',
  'Starlight',
  'Happy Hollow',
]

module.exports.places = [
  'Camp Haven',
  'Pine Valley',
  "River's Edge",
  'Sunset Pines',
  'Lakeview Retreat',
  'Mountain Meadows',
  'Hidden Oasis',
  'Whispering Woods',
  'Wilderness Escape',
  'Serenity Springs',
  "Nature's Trail",
  'Rustic Ridge',
  'Lakeside Haven',
  'Adventure Camp',
  'Starlight Grove',
  'Wildflower Meadow',
  'Shady Oaks',
  'Happy Hollow',
  'Tranquil Waters',
  'Campfire Cove',
]

module.exports.descriptions = [
  'Nestled in a pine forest, this campground offers serene beauty and abundant wildlife.',
  'A waterfront oasis, perfect for fishing and kayaking enthusiasts.',
  "This remote campground is a stargazer's dream with minimal light pollution.",
  'Family-friendly campground with a playground and nature trails.',
  'An RV haven with full hookups and stunning mountain views.',
  'A historic site where you can camp among ancient ruins.',
  'Secluded campground for those seeking solitude and peaceful hikes.',
  'Lakeside camping with access to a sandy beach for swimming.',
  'A dog-friendly campground with a spacious pet play area.',
  'Camp in the heart of wine country with vineyard views.',
  'Riverside sites for anglers and water-loving campers.',
  "A rock climber's paradise with boulders right at your campsite.",
  'A desert oasis known for its cactus gardens and starry nights.',
  'This campground features natural hot springs for ultimate relaxation.',
  'Camp along the Appalachian Trail and hike to scenic overlooks.',
  'A historic Civil War battleground turned campground with guided tours.',
  'Camp in the shadow of a volcano with hiking trails and lava fields.',
  'Enjoy the sound of crashing waves at this beachfront campground.',
  'A horse-friendly campground with equestrian trails and corrals.',
  'Camp among the redwoods in a lush California forest.',
  'Waterfront camping for boaters and anglers.',
  "A birdwatcher's paradise with numerous species to observe.",
  'Camp in a canyon surrounded by towering cliffs and waterfalls.',
  'An eco-friendly campground committed to sustainable practices.',
  'Camp in the Smoky Mountains with access to scenic drives.',
  'A winter wonderland for snow sports and cozy campfires.',
  'A desert escape with colorful sunsets and cacti gardens.',
  'Riverside camping with tubing and water recreation.',
  'Camp on a historic farm and participate in farm-to-table activities.',
  'Secluded beach camping for those seeking solitude.',
  'Camp in the heart of a national park with wildlife sightings.',
  "A fishing enthusiast's dream with stocked ponds and rivers.",
  'A basecamp for rock climbers with challenging routes nearby.',
  'Camp along the Pacific Coast Highway with ocean views.',
  'RV-friendly sites with amenities like pools and hot tubs.',
  'A rustic campground with access to backcountry hiking.',
  'Enjoy fall foliage at its finest in this autumnal paradise.',
  'A canoe and kayak haven with easy water access.',
  'Camp in the shadow of a lighthouse and explore coastal trails.',
  'A rustic retreat with simple campsites and natural beauty.',
  'A forested campground with interpretive nature programs.',
  'Camp in a desert oasis with palm trees and desert flowers.',
  'A mountain hideaway known for its pristine alpine lakes.',
  'Camp along the shores of a crystal-clear mountain lake.',
  'A cultural experience with Native American heritage programs.',
  "A camper's paradise with access to extensive hiking trails.",
  'Camp in a vineyard and enjoy wine tastings at sunset.',
  'A fishing and boating destination with marina facilities.',
  "A hiker's dream with access to a network of trails.",
  'A beachfront campground with volleyball courts and bonfire pits.',
]

module.exports.prices = [
  100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350, 375, 400,
]
