module.exports.descriptors = [
  'Whispering',
  'Pine',
  'Meadow',
  'Riverbend',
  'Sunset',
  'Lakeside',
  'Mountainview',
  'Hidden',
  'Tranquil',
  'Rustic',
  'Serene',
  'Wilderness',
  'Oasis',
  "Nature's",
  'Timber',
  'Wildflower',
  'Shady',
  'Adventure',
  'Starlight',
  'Happy Hollow',
]

module.exports.places = [
  'Camp Haven',
  'Pine Valley',
  "River's Edge",
  'Sunset Pines',
  'Lakeview Retreat',
  'Mountain Meadows',
  'Hidden Oasis',
  'Whispering Woods',
  'Wilderness Escape',
  'Serenity Springs',
  "Nature's Trail",
  'Rustic Ridge',
  'Lakeside Haven',
  'Adventure Camp',
  'Starlight Grove',
  'Wildflower Meadow',
  'Shady Oaks',
  'Happy Hollow',
  'Tranquil Waters',
  'Campfire Cove',
]

module.exports.descriptions = [
  "Nature's sanctuary for outdoor enthusiasts.",
  'A tranquil escape amidst scenic beauty.',
  'Where adventure meets the great outdoors.',
  'Discover the serenity of camping in the wilderness.',
  'Embrace the rustic charm of nature.',
  'A haven for campers seeking peace and quiet.',
  'Camp under starlit skies and reconnect with nature.',
  'Immerse yourself in the beauty of untouched landscapes.',
  'Where campfires and stories create lasting memories.',
  'Wake up to the soothing sounds of nature.',
  'Explore endless trails and hidden wonders.',
  'Experience the joy of sleeping under a canopy of trees.',
  'A playground for outdoor recreation and relaxation.',
  'Connect with nature and unplug from the modern world.',
  'Escape the hustle and bustle and find solace in the wilderness.',
  'Let the wilderness awaken your sense of adventure.',
  'Dive into the beauty and tranquility of natural surroundings.',
  'Recharge your soul with fresh air and open spaces.',
  'Campground bliss: a perfect blend of nature and comfort.',
  'Where campers become one with the great outdoors.',
]

module.exports.prices = ['100', '125', '150', '200', '250', '300', '325']
